---

- name: Desinstalar Apache en webservers y elimina el soporte PHP
  hosts: webservers
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 

  - name: Desinstala Apache2
    apt:
      name: apache2
      state: absent
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: Remueve soporte PHP para Apache2
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Desinstala Nginx de databases
  hosts: databases
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Desinstala nginx
    apt: 
      name: nginx
      state: absent

  - name: Detiene nginx
    service:
      name: nginx
      state: stopped

